name = "leancolls"
defaultTargets = ["LeanColls"]

[[require]]
name = "mathlib"
git  = "https://github.com/leanprover-community/mathlib4"
rev  = "v4.8.0-rc1"

[[lean_lib]]
name = "LeanColls"

[[lean_exe]]
name = "test"
root = "Main"

