name = "leancolls"
defaultTargets = ["LeanColls"]

[[require]]
name = "mathlib"
git  = "https://github.com/leanprover-community/mathlib4"
rev  = "master"

[[lean_lib]]
name = "LeanColls"

[[lean_exe]]
name = "test"
root = "Main"

