name: Build library & docs

on:
  push:
  pull_request:

jobs:
  build:
    name: Build library & docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build library
        run: |
          lake exe cache get
          lake build LeanColls

      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: .lake/build/lib

      - name: Generate docs
        run: |
          lake build -R -Kdoc=on LeanColls:docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: .lake/build/doc

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest

    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Reset gh-pages to main
        run: |
          git fetch origin main
          git reset --hard main

      - name: Download docs artifact
        uses: actions/download-artifact@master
        with:
          name: docs
          path: docs/docs

      - name: Force push to gh-pages branch
        run: |
          git add docs/*
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Automatic docs update $git_hash"
          git push -f
