name: Build library & docs

on:
  push: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build library
        run: |
          lake exe cache get
          lake build LeanColls

      - name: Generate docs
        run: |
          lake build -R -Kdoc=on LeanColls:docs

      - name: Deploy docs and push to gh-pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout gh-pages
          git reset --hard main
          mv .lake/build/doc docs/docs/
          git add docs/*
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git commit -m "Automatic docs update $git_hash"
          git push -f
