name: Rebase mathlib-nightly

on:
  push:
    branches:
      - main

jobs:
  rebase_mathlib_nightly:
    name: Rebase mathlib-nightly onto main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JAMES_PAT }}
          ref: mathlib-nightly
          fetch-depth: 0

      - name: Rebase onto main
        run: |
          git rebase origin/main
          git push -f
