name: Rebase mathlib-nightly

on:
  push:
    branches:
      - main

jobs:
  rebase_mathlib_nightly:
    name: Rebase mathlib-nightly onto main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JAMES_PAT }}
          ref: mathlib-nightly

      - name: Fetch main and merge base
        run: |
          git fetch origin main
          MAIN_COMMIT=$(git rev-parse origin/main)
          NIGHTLY_COMMIT=$(git rev-parse mathlib-nightly)
          echo "main: $MAIN_COMMIT"
          echo "mathlib-nightly: $NIGHTLY_COMMIT"
          cmd="curl -s -H 'Authorization: token $GITHUB_TOKEN' \
              'https://api.github.com/repos/my_user/my_repo/compare/$MAIN_COMMIT...$NIGHTLY_COMMIT'
            | jq -r '.merge_base_commit.sha'"
          MERGE_BASE=$(eval "$cmd")
          echo "merge base: $MERGE_BASE"
          echo "MERGE_BASE=$MERGE_BASE" >> $GITHUB_ENV
          git fetch \
            --no-tags \
            --prune \
            --progress \
            --no-recurse-submodules \
            --depth=1 \
            origin $MERGE_BASE

      - name: Rebase onto main
        run: |
          git rebase --onto "$MERGE_BASE" origin/main
          git push -f
