name: Rebase mathlib-nightly

on:
  push:
    branches:
      - main

jobs:
  rebase_mathlib_nightly:
    name: Rebase mathlib-nightly onto main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JAMES_PAT }}
          ref: mathlib-nightly
      - name: Rebase onto main
        run: |
          git fetch origin main
          echo "on $(git rev-parse --symbolic-full-name HEAD) at $(git rev-parse HEAD)"
          echo "origin/main is at $(git rev-parse origin/main)"
          git rebase origin/main
          git push -f
